# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SwiftBuild:
    name: Swift Build and Unit Tests

    runs-on: macos-latest

    steps:
      - name: Get swift version
        run: swift --version
      - uses: actions/checkout@master
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --parallel
    # - name: Checkout
    #   uses: actions/checkout@v3
    # - name: Build
    #   run: swift build -v
    # - name: Run tests
    #   run: swift test -v
      
  SwiftPackageValidation:
    name: Validate Swift package
    
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Swift Package
        run: swift package generate-xcodeproj
